// require("../assets/images/logoresto.jpg");

export const restaurantData = [
  {
    id: 1,
    ouvert: true,
    nomResto: "Chez Karim",
    town: "Bafoussam",
    localisation: "Derriere marche A",
    imgAdmin: "/assets/images/admin.jpg",
    imgResto: "/assets/images/resto1.jpg",
    horraire: "08-17h",
    menu: [
      {
        nom: "Porc braiser",
        prix: 1400,
        id: 1,
        imgMenu: "/assets/images/eru.jpg",
        desc: "Lörem ipsum rev povåd krost. Telerat krislåda. Metrologi lalogioliga det rett kontrahögisk. Jytör",
      },
      {
        nom: "Taro sauce jaune",
        prix: 2500,
        imgMenu: "/assets/images/eru.jpg",
        id: 2,
        desc: "Lörem ipsum rev povåd krost. Telerat krislåda. Metrologi lalogioliga det rett kontrahögisk. Jytör",
      },
    ],
  },
  {
    id: 1,
    ouvert: true,
    nomResto: "Chez Karim",
    town: "Bafoussam",
    localisation: "Derriere marche A",
    imgAdmin: "/assets/images/admin.jpg",
    imgResto: "/assets/images/resto1.jpg",
    horraire: "08-17h",
    menu: [
      {
        nom: "Porc braiser",
        prix: 1400,
        id: 1,
        imgMenu: "/assets/images/eru.jpg",
        desc: "Lörem ipsum rev povåd krost. Telerat krislåda. Metrologi lalogioliga det rett kontrahögisk. Jytör",
      },
      {
        nom: "Taro sauce jaune",
        prix: 2500,
        imgMenu: "/assets/images/eru.jpg",
        id: 2,
        desc: "Lörem ipsum rev povåd krost. Telerat krislåda. Metrologi lalogioliga det rett kontrahögisk. Jytör",
      },
    ],
  },
  {
    id: 1,
    ouvert: true,
    nomResto: "Chez Karim",
    town: "Bafoussam",
    localisation: "Derriere marche A",
    imgAdmin: "/assets/images/admin.jpg",
    imgResto: "/assets/images/resto1.jpg",
    horraire: "08-17h",
    menu: [
      {
        nom: "Porc braiser",
        prix: 1400,
        id: 1,
        imgMenu: "/assets/images/eru.jpg",
        desc: "Lörem ipsum rev povåd krost. Telerat krislåda. Metrologi lalogioliga det rett kontrahögisk. Jytör",
      },
      {
        nom: "Taro sauce jaune",
        prix: 2500,
        imgMenu: "/assets/images/eru.jpg",
        id: 2,
        desc: "Lörem ipsum rev povåd krost. Telerat krislåda. Metrologi lalogioliga det rett kontrahögisk. Jytör",
      },
    ],
  },
  {
    id: 1,
    ouvert: true,
    nomResto: "Chez Karim",
    town: "Bafoussam",
    localisation: "Derriere marche A",
    imgAdmin: "/assets/images/admin.jpg",
    imgResto: "/assets/images/resto1.jpg",
    horraire: "08-17h",
    menu: [
      {
        nom: "Porc braiser",
        prix: 1400,
        id: 1,
        imgMenu: "/assets/images/eru.jpg",
        desc: "Lörem ipsum rev povåd krost. Telerat krislåda. Metrologi lalogioliga det rett kontrahögisk. Jytör",
      },
      {
        nom: "Taro sauce jaune",
        prix: 2500,
        imgMenu: "/assets/images/eru.jpg",
        id: 2,
        desc: "Lörem ipsum rev povåd krost. Telerat krislåda. Metrologi lalogioliga det rett kontrahögisk. Jytör",
      },
    ],
  },
  {
    id: 1,
    ouvert: true,
    nomResto: "Chez Karim",
    town: "Bafoussam",
    localisation: "Derriere marche A",
    imgAdmin: "/assets/images/admin.jpg",
    imgResto: "/assets/images/resto1.jpg",
    horraire: "08-17h",
    menu: [
      {
        nom: "Porc braiser",
        prix: 1400,
        id: 1,
        imgMenu: "/assets/images/eru.jpg",
        desc: "Lörem ipsum rev povåd krost. Telerat krislåda. Metrologi lalogioliga det rett kontrahögisk. Jytör",
      },
      {
        nom: "Taro sauce jaune",
        prix: 2500,
        imgMenu: "/assets/images/eru.jpg",
        id: 2,
        desc: "Lörem ipsum rev povåd krost. Telerat krislåda. Metrologi lalogioliga det rett kontrahögisk. Jytör",
      },
    ],
  },
  {
    id: 1,
    ouvert: true,
    nomResto: "Chez Karim",
    town: "Bafoussam",
    localisation: "Derriere marche A",
    imgAdmin: "/assets/images/admin.jpg",
    imgResto: "/assets/images/resto1.jpg",
    horraire: "08-17h",
    menu: [
      {
        nom: "Porc braiser",
        prix: 1400,
        id: 1,
        imgMenu: "/assets/images/eru.jpg",
        desc: "Lörem ipsum rev povåd krost. Telerat krislåda. Metrologi lalogioliga det rett kontrahögisk. Jytör",
      },
      {
        nom: "Taro sauce jaune",
        prix: 2500,
        imgMenu: "/assets/images/eru.jpg",
        id: 2,
        desc: "Lörem ipsum rev povåd krost. Telerat krislåda. Metrologi lalogioliga det rett kontrahögisk. Jytör",
      },
    ],
  },
  {
    id: 1,
    ouvert: true,
    nomResto: "Chez Karim",
    town: "Bafoussam",
    localisation: "Derriere marche A",
    imgAdmin: "/assets/images/admin.jpg",
    imgResto: "/assets/images/resto1.jpg",
    horraire: "08-17h",
    menu: [
      {
        nom: "Porc braiser",
        prix: 1400,
        id: 1,
        imgMenu: "/assets/images/eru.jpg",
        desc: "Lörem ipsum rev povåd krost. Telerat krislåda. Metrologi lalogioliga det rett kontrahögisk. Jytör",
      },
      {
        nom: "Taro sauce jaune",
        prix: 2500,
        imgMenu: "/assets/images/eru.jpg",
        id: 2,
        desc: "Lörem ipsum rev povåd krost. Telerat krislåda. Metrologi lalogioliga det rett kontrahögisk. Jytör",
      },
    ],
  },
  {
    id: 1,
    ouvert: true,
    nomResto: "Chez Karim",
    town: "Bafoussam",
    localisation: "Derriere marche A",
    imgAdmin: "/assets/images/admin.jpg",
    imgResto: "/assets/images/resto1.jpg",
    horraire: "08-17h",
    menu: [
      {
        nom: "Porc braiser",
        prix: 1400,
        id: 1,
        imgMenu: "/assets/images/eru.jpg",
        desc: "Lörem ipsum rev povåd krost. Telerat krislåda. Metrologi lalogioliga det rett kontrahögisk. Jytör",
      },
      {
        nom: "Taro sauce jaune",
        prix: 2500,
        imgMenu: "/assets/images/eru.jpg",
        id: 2,
        desc: "Lörem ipsum rev povåd krost. Telerat krislåda. Metrologi lalogioliga det rett kontrahögisk. Jytör",
      },
    ],
  },
  {
    id: 1,
    ouvert: true,
    nomResto: "Chez Karim",
    town: "Bafoussam",
    localisation: "Derriere marche A",
    imgAdmin: "/assets/images/admin.jpg",
    imgResto: "/assets/images/resto1.jpg",
    horraire: "08-17h",
    menu: [
      {
        nom: "Porc braiser",
        prix: 1400,
        id: 1,
        imgMenu: "/assets/images/eru.jpg",
        desc: "Lörem ipsum rev povåd krost. Telerat krislåda. Metrologi lalogioliga det rett kontrahögisk. Jytör",
      },
      {
        nom: "Taro sauce jaune",
        prix: 2500,
        imgMenu: "/assets/images/eru.jpg",
        id: 2,
        desc: "Lörem ipsum rev povåd krost. Telerat krislåda. Metrologi lalogioliga det rett kontrahögisk. Jytör",
      },
    ],
  },
  {
    id: 2,
    ouvert: false,
    nomResto: "Net Net Resto",
    imgAdmin: "/assets/images/admin.jpg",
    imgResto: "/assets/images/resto2.jpg",
    town: "Douala",
    localisation: "Rond point total",
    horraire: "08-16h",
    menu: [
      {
        nom: "ara braiser avec patate rouge",
        prix: 1200,
        id: 1,
        imgMenu: "/assets/images/okok.jpg",
        desc: "Lörem ipsum rev povåd krost. Telerat krislåda. Metrologi lalogioliga det rett kontrahögisk. Jytör",
      },
      {
        nom: "Taro sauce jaune",
        imgMenu: "/assets/images/taro.jpg",
        prix: 2500,
        id: 2,
        desc: "Lörem ipsum rev povåd krost. Telerat krislåda. Metrologi lalogioliga det rett kontrahögisk. Jytör",
      },
      {
        nom: "Gari and eru",
        prix: 1500,
        imgMenu: "/assets/images/eru.jpg",
        id: 3,
        desc: "Lörem ipsum rev povåd krost. Telerat krislåda. Metrologi lalogioliga det rett kontrahögisk. Jytör",
      },
    ],
  },
  {
    id: 3,
    ouvert: false,
    nomResto: "Restaurant le Restoration",
    imgAdmin: "/assets/images/admin.jpg",
    imgResto: "/assets/images/resto3.jpg",
    town: "Bafoussam",
    localisation: "Feu rouge",
    horraire: "09-15h",
    menu: [
      {
        nom: "Riz braiser",
        prix: 1200,
        id: 1,
        imgMenu: "/assets/images/eru.jpg",
        desc: "Lörem ipsum rev povåd krost. Telerat krislåda. Metrologi lalogioliga det rett kontrahögisk. Jytör",
      },
      {
        nom: "Taro sauce jaune",
        prix: 2500,
        id: 2,
        imgMenu: "/assets/images/taro.jpg",
        desc: "Lörem ipsum rev povåd krost. Telerat krislåda. Metrologi lalogioliga det rett kontrahögisk. Jytör",
      },
      {
        nom: "Gari and eru",
        prix: 1500,
        id: 3,
        imgMenu: "/assets/images/okok.jpg",
        desc: "Lörem ipsum rev povåd krost. Telerat krislåda. Metrologi lalogioliga det rett kontrahögisk. Jytör",
      },
    ],
  },
];
